### ISSUE TITLE
Use `Object.getOwnPropertyDescriptors`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/filter-obj#24]
Instead of using `Reflect.ownKeys` and then `Object.getOwnPropertyDescriptor` (one), why not just get `Object.getOwnPropertyDescriptors` (multiple) and loop that?

Similarly, you could use `Object.defineProperties` instead of `Object.defineProperty` to create the object in one pass after mapping the result of the previous function.

**Comment by sindresorhus** [comment]
// @ehmicky

**Comment by ehmicky** [comment]
Nice idea @fregante!
I have tried it out in https://github.com/sindresorhus/filter-obj/pull/25, but it seems like this would be roughly twice slower. The main reason is because `Reflect.ownKeys()` would still be needed to iterate over the object returned by `Object.getOwnPropertyDescriptors()`, including symbols.

**Comment by fregante** [comment]
Is there any alternative API that returns that as entries Set instead of an Object? Other than that…

![ccle328l1iq21](https://user-images.githubusercontent.com/1402241/181270126-a165f7f2-a8a4-4679-815c-4c49430976c0.jpg)

**Comment by ehmicky** [comment]
Yes, it's too bad this does not exist :(. 
That being said, I have also opened https://github.com/sindresorhus/filter-obj/pull/26 which is provides with a small performance boost inspired by your initial post, by re-using the descriptor `enumerable` property instead of calling `Object.prototype.propertyIsEnumerable()`.

**Comment by ehmicky** [comment]
@fregante Based on the above, do you think we should maybe close the issue?
