### ISSUE TITLE
Allow any type of iterable

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/filter-obj#29]
A consumer may want to use a `Set` instead of an array for filtering keys. We could allow for iterables to be provided.

**Comment by ehmicky** [comment]
Great idea! I have opened a PR at #30.

**Comment by sindresorhus** [comment]
The only downside I can think of is that `string` is an iterable, so even in TypeScript, users could accidentally pass the incorrect thing.

**Comment by ehmicky** [comment]
That's a good point. We could prevent this by:
  - Throwing an error when the input is a `string`
  - Updating the TypeScript types to use `Exclude<Iterator<...>, string>` ([example playground](https://www.typescriptlang.org/play?ssl=1&ssc=1&pln=2&pc=1#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXy3QmVAGkQBPAZwB4AoASAHkAjAK3AwBUKAHBEAA8MIVMCrwASuBwxgNAAowc-GBgrkKAGnhRUFAHxbGASSIkQwTRKEixEgNaUcieKw6Ye-YwYAUjHHZOAC43IM8+EGMGJ2pQgFFBSAsaaShgPAgKGhMRGCgWCBAc81ArSioDI3gqDBhCAHMDOgBKUIUsMAcad04vKPgzZLLrAwBuOjpCYZBrXwBvXVC65AQAXx0AcihNlqA))

What do you think?

**Comment by sindresorhus** [comment]
The problem then is the cascading effect. Anything that calls it has to know the exact behavior. For example, you cannot just pass through iterators then. It also complicates TypeScript usage. It means anything that calls it has to exclude `string` from the iterable type.

So I think, either we accept that string can accidentally be passed or we stay with array.

**Comment by ehmicky** [comment]
This makes sense. :+1: 

Also, it turns out: the types already forbid a `keys` argument which target keys not known in the `object` argument. For example, `includeKeys({ one: true }, 'ab')` will fail because neither `'a'` nor `'b'` is a property in `{ one: true }`.

In other words, a `string` cannot transtype to a `Iterator<IncludedKeys>`, providing `IncludedKeys` is a union of literal types. For example, with an `object` like `{ one: true, two: true }`, `IncludedKeys` would be `"one" | "two"`, and `string` cannot transtype to `Iterator<"one" | "two">`. However, that does not work if the object has an index string type like `{ [index: string]: any }`, in which case `string` will correctly transtype to `Iterator<string>`. 

This should limit most errors with TypeScript users (but not non-TypeScript users).

Another option would be to keep things as is and not allow iterables. What do you think @sindresorhus and @Richienb?

**Comment by Richienb** [comment]
In that case, change the PR so that it adds support for only `Set`s and not iterables in general.

**Comment by sindresorhus** [comment]
I think we should just keep it like it is. It's just a small convenience anyway.

**Comment by sindresorhus** [comment]
> In that case, change the PR so that it adds support for only Sets and not iterables in general.

The general convention is to use array for inputs. I don't know any API that accepts both array and set. Maybe it would make sense if the API got a significant performance boost by doing so, but I think we should just keep it simple.

**Comment by sindresorhus** [comment]
Additional thought: I think where it makes sense to accept iterables is when it's expensive to get the elements, so it can be lazily iterated, but that's not the case here.

**Comment by ehmicky** [comment]
This makes sense. :+1: 

I have a library that I split into two based on whether the input was an array or not: [`fast-cartesian`](https://github.com/ehmicky/fast-cartesian) and [`big-cartesian`](https://github.com/ehmicky/big-cartesian). The reason for using iterables there was to reduce memory consumption (like streams) and to overcome the maximum size of array.

But in the context of `filter-obj`, it does seem like letting users spread their iterable into an array is best and keeps this library simpler.
